# Generated by Django 2.0 on 2019-01-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名字')),
                ('publish', models.CharField(max_length=32, verbose_name='发表')),
                ('author', models.CharField(max_length=32, verbose_name='作者')),
                ('price', models.IntegerField(default=0, verbose_name='价格')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
            },
        ),
    ]
