# Generated by Django 2.0 on 2019-01-11 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='', max_length=32, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish',
            field=models.CharField(blank=True, max_length=32, verbose_name='发表'),
        ),
    ]
